version: "3.8"

services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - etl_network
    command:
      -p ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
  
  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    expose:
      - "9200"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - etl_network
  
  etl:
    container_name: etl
    build: ../postgres_to_es/
    networks:
      - etl_network
    env_file:
      - ./.env
    depends_on:
      elasticsearch:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  db_value:

networks:
  etl_network:
